void gser(double *gamser, double a, double x, double *gln);
void gcf(double *gammcf, double a, double x, double *gln);
void reg_linear (double x[], double y[], int ndata, double *a, double *b, double *F, double *P);
void avevar(double *data, long n, double *ave, double *var);
void avevar2(double *data, int n, double *ave, double *var);
void moment(double data[], int n, double *ave, double *adev, double *sdev, double *var, double *skew, double *curt);
void ttest_onesample (double data[], long n, double expected, double *t, double *p);
void ttest_ev(double data1[], long n1, double data2[], long n2, double *t, double *p);
void ttest_uev(double data1[], long n1, double data2[], long n2, double *t, double *p);
void ftest(double data1[], long n1, double data2[], long n2, double *f, double *p);
void chi2test(double bins1[], double bins2[], int nbins, int knstrn, double *df, double *chi2, double *p);
void chi2test_onesample(double bins[], double ebins[], int nbins, int knstrn, double *df, double *chi2, double *p);
void chi2test_2by2table(double bins[], double *chi2, double *p);
void chi2test_2by3table(double bins[], double *chi2, double *p);
void kstest(double data1[], long n1, double data2[], long n2, double *d, double *prob);
void kstest_onesample(double data[], long n, double (*func)(double), double *d, double *prob);
void quick_sort(int elements, double *arr);
double fisher_exact_1sided (int a, int b, int c, int d);
double fisher_exact_2sided (int a, int b, int c, int d);

double gammln(double x);
double lnfactorial (double x);
int factorial (int x);
double gammp(double a, double x);
double gammq(double a, double x);
double beta(double z, double w);
double betai(double a, double b, double x);
double betacf(double a, double b, double x);
double inverff (double x);
double erf(double x);
double cdf_binomial (int n, int k, double p);
double cdf_chi2 (double df, double x);
double cdf_poisson (int k, double x);
double cdf_normal (double x, double mu, double sigma);
double cdf_stdnormal (double x);
double invnormal (double x);
double pdf_stdnormal (double x);
double pdf_normal (double x, double mu, double sigma);
double pdf_beta (double a, double b, double x);
double bico (int n, int k);
double pdf_binomial (int n, int k, double p);
double cdf_f (double df1, double df2, double x);
double cdf_t (double df, double x);
double mean(double *data, int n);
double mean2(double *data, int n);
double probks(double alam);
float ran3(long *idum);
double random_exp(double lamda, long *idum);
float random_stdnormal (long *idum);

double SNPHWE(int obs_hets, int obs_hom1, int obs_hom2);

FILE *fh_stdout ();
FILE *fh_stderr ();
